# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wiki.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 273)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 471, 241))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame {\n"
" background-color: #F0F0F0 \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 90, 81, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 150, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 30, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(80, 60, 31, 16))
        self.label_6.setObjectName("label_6")
        self.inputfile_dir = QtWidgets.QLineEdit(self.frame)
        self.inputfile_dir.setGeometry(QtCore.QRect(110, 90, 271, 20))
        self.inputfile_dir.setObjectName("inputfile_dir")
        self.yes_button = QtWidgets.QRadioButton(self.frame)
        self.yes_button.setGeometry(QtCore.QRect(110, 150, 89, 16))
        self.yes_button.setObjectName("yes_button")
        self.no_button = QtWidgets.QRadioButton(self.frame)
        self.no_button.setGeometry(QtCore.QRect(210, 150, 89, 16))
        self.no_button.setObjectName("no_button")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(110, 30, 271, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(110, 60, 271, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.inputfile_button = QtWidgets.QToolButton(self.frame)
        self.inputfile_button.setGeometry(QtCore.QRect(390, 90, 51, 20))
        self.inputfile_button.setObjectName("inputfile_button")
        self.tips = QtWidgets.QLabel(self.frame)
        self.tips.setGeometry(QtCore.QRect(110, 120, 231, 16))
        self.tips.setStyleSheet("QLabel{\n"
"    color: rgb(255, 0, 0);\n"
"    font: 75 9pt \"Agency FB\";\n"
"}")
        self.tips.setObjectName("tips")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(150, 180, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.notice = QtWidgets.QLabel(self.frame)
        self.notice.setGeometry(QtCore.QRect(80, 210, 311, 16))
        self.notice.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.notice.setStyleSheet("QLabel{\n"
"    color: rgb(255, 0, 0);\n"
"    font: 75 12pt \"Agency FB\";\n"
"    font-weight: bold;\n"
"}")
        self.notice.setText("")
        self.notice.setAlignment(QtCore.Qt.AlignCenter)
        self.notice.setObjectName("notice")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(-220, 850, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "批量导入"))
        self.label.setText(_translate("MainWindow", "文件输入目录"))
        self.label_4.setText(_translate("MainWindow", "是否覆盖"))
        self.label_5.setText(_translate("MainWindow", " 用户名"))
        self.label_6.setText(_translate("MainWindow", "密码"))
        self.inputfile_dir.setPlaceholderText(_translate("MainWindow", "请选择输入文件目录"))
        self.yes_button.setText(_translate("MainWindow", "是"))
        self.no_button.setText(_translate("MainWindow", "否"))
        self.username.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.password.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.inputfile_button.setText(_translate("MainWindow", "..."))
        self.tips.setText(_translate("MainWindow", "* 文件输出目录会自动添加到此输入目录下"))
